on: issues
name: Issues
jobs:
  issueHandler:
    name: IssueHandler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: IssueHandler
        uses: Ash258/Scoop-GithubActions@stable
        env:
          GITH_EMAIL: hi@iszy.xyz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
