on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: shovel-org/GithubActions@main
        env:
          GITH_EMAIL: hi@iszy.xyz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
